### PR TITLE
IE11 Support

### PR DESCRIPTION
**Pull request by ewlarson**
WIP

Adds polyfills and a babel-fied version of blacklight.js locally to support IE11. Also closes an svg path element. Not certain this covers all the ills, but is a good start.

Would definitely want to remove this local override when migrating to webpacker and proper transpiling.

### CODE REVIEW

**Comment by ewlarson** [comment]
ie11_support

**Review by little9 — APPROVED** [review]
I like this approach for now. When we do another big upgrade we should move to the webpacker approach, but it will probably take some work to get all the old JS and the custom CSS working correctly.

**Comment by jhu-alistair** [comment]
What problem is this fixing?

**Comment by ewlarson** [comment]
@jhu-alistair Blacklight ships with javascript that IE11 does not support, examples: arrow functions, array.from, and let variables. This PR adds a local blacklight.js file with javascript transpiled and polyfilled that IE11 can handle.

Basically, you'd get IE11 support going down this route.

**Comment by fackrellj** [comment]
I'll make a note about this so we don't forget is it needs to be removed when we transition to webpacker or that it might need updated if we update blacklight again before that.

**Pull request merged**
